### ISSUE TITLE
Replace all Wenyanngat graphics

### ISSUE THREAD

**Issue by KEKS1C** [East-Showdown/ukraine#3]
Так как теперь у нас нету прав на работы Wenyanngat
, нам нужно заменить абсолютно всю графику сделанную им, чтобы не нарушать авторские права.

Since we now have no rights to the works of Wenyanngat
, we need to replace absolutely all the graphics made by him in order not to violate the copyright.

**Comment by Tllya** [comment]
Веня разрешил использовать его графику, поэтому я считаю что это не нужно
