### ISSUE TITLE
у вас нет прав

### ISSUE THREAD

**Issue by Poxuy1** [East-Showdown/ukraine#30]
верните

**Comment by Poxuy1** [comment]
не пон

**Comment by LLawee** [comment]
ааааоооаоа

**Comment by LLawee** [comment]
работает?

**Comment by Poxuy1** [comment]
ребята завтра в 12:00 все в войсе одкб, у нас митинг в честь того что нам не дают норм ии для рф 🆘🆘🆘🆘🆘

**Comment by Poxuy1** [comment]
да брат

**Comment by Poxuy1** [comment]
мы на телеке

**Comment by LLawee** [comment]
ооо супер

**Comment by Poxuy1** [comment]
ну как у тебя дела ваще

**Comment by LLawee** [comment]
спамить надо

**Comment by LLawee** [comment]
пока есть шанс

**Comment by Glovyss** [comment]
о нет

**Comment by Poxuy1** [comment]
не надо спамить бро

**Comment by Poxuy1** [comment]
давайте пообщаемся

**Comment by LLawee** [comment]
ладно

**Comment by LLawee** [comment]
э

**Comment by Poxuy1** [comment]
ЭЭ НАХУЙ ТЫ ЧЕ

**Comment by LLawee** [comment]
у нас есть права

**Comment by Poxuy1** [comment]
Я ТЕБЕ АТАКУ ЯДЕРНУЮ СТРОЮ БЛЯТЬ 🆘🆘🆘

**Comment by Poxuy1** [comment]
<@553511592940011522>

**Comment by Poxuy1** [comment]
<@553511592940011522>

**Comment by Poxuy1** [comment]
<@553511592940011522>

**Comment by Poxuy1** [comment]
ладно

**Comment by Glovyss** [comment]
жиза

**Comment by Poxuy1** [comment]
пацаны короче прикиньте я летом живу в саду

**Comment by Poxuy1** [comment]
ладно

**Comment by Poxuy1** [comment]
короче бассейн есть

**Comment by LLawee** [comment]
начали удалять?

**Comment by Poxuy1** [comment]
и он короче зеленый был типо зацвел типо

**Comment by Poxuy1** [comment]
не забей

**Comment by Poxuy1** [comment]
все норм

**Comment by LLawee** [comment]
открыл зач

**Comment by Poxuy1** [comment]
мы власть ребята завтра в 12:00 все в войсе одкб, у нас митинг в честь того что нам не дают норм ии для рф 🆘🆘🆘🆘🆘

**Comment by LLawee** [comment]
и что это дает

**Comment by Glovyss** [comment]
ии уже должен нормально работать

**Comment by Poxuy1** [comment]
Я ДО ПОСЛЕДНЕГО НАДЕЯЛСЯ ЧТО ОНИ НЕ ВЫКЛЮЧАТ ПУНКТ В ВЕБХУКЕ БЛЯТЬ
ФХРАХРФХРХФРХХРФРФРФАР

**Comment by Glovyss** [comment]
я пофиксил, щас тестить будут

**Comment by Poxuy1** [comment]
рил?

**Comment by LLawee** [comment]
и что нам будет

**Comment by Poxuy1** [comment]
бля я надеюсь ты сделаешь все по кайфу

**Comment by Poxuy1** [comment]
жалко что больше не напишем

**Comment by LLawee** [comment]
(

**Comment by Glovyss** [comment]
короче, да, есть же дс

**Comment by Poxuy1** [comment]
бро

**Comment by Poxuy1** [comment]
все по кайфу

**Comment by Poxuy1** [comment]
мы проиграли бой а не войну

**Comment by Poxuy1** [comment]
они вырубили все сообщения гитхаба

**Comment by Poxuy1** [comment]
а не только комменты

**Comment by Poxuy1** [comment]
и им рано или поздно надо их включить будет

**Comment by Poxuy1** [comment]
мы проиграли только бой, все под контролем
