### ISSUE TITLE
Бунт против лидов. (Добавляю все что захочу потому что нету связи)

### ISSUE THREAD

**Issue by Vlad189** [East-Showdown/ukraine#33]
Пан никанин замутил меня на 1 день. Теперь связь с лидами потерялась никто не хочет её восстановить теперь я добавляю все что захочу!

**Comment by Vlad189** [comment]
Теперь ни с кем не посоветуешься так пан никанин меня замутил а значит можно добавить систему боеприпасов!

**Comment by jjjjj888885** [comment]
Добавь систему недовольства украинцев,типа взял киев и там решения Начать жоско действовать или успокоить и сделать все мирно и  добится подчинения

**Comment by Conteyner** [comment]
Хуета, в Украине такого нету.

**Comment by jjjjj888885** [comment]
бунт
бунт

**Comment by jjjjj888885** [comment]
хочу попу контейнера
